pipelineAccount:
  awsAccountId: 374307543222
  awsRegion: ap-south-1

devAccount:
  awsAccountId: 374307543222
  awsRegion: ap-south-1

prodAccount:
  awsAccountId: 374307543222
  awsRegion: ap-south-1

dev:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json

prod:
  jobs:
    ProcessLegislators:
      inputLocation: s3://awsglue-datasets/examples/us-legislators/all/persons.json