version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      # Install CDK CLI globally with WebAssembly support
      - npm install -g aws-cdk
      # Create and activate virtual environment
      - python -m venv .venv
      - source .venv/bin/activate
      # Install Python dependencies
      - pip install -r requirements-dev.txt
      - pip install -r requirements.txt
  build:
    commands:
      # Activate virtual environment
      - source .venv/bin/activate
      # Run CDK synthesis with WebAssembly experimental flags
      - node --experimental-wasm-reftypes $(which cdk) synth -c stage=dev
artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
  name: GlueAppArtifact