version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing CDK and dependencies..."
      - npm install aws-cdk@2     # ✅ local install only
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt

  build:
    commands:
      - source .venv/bin/activate
      - echo "Running cdk synth with npx..."
      - npx cdk synth -c stage=dev     # ✅ uses local CDK CLI and Node.js 18

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
  name: GlueAppArtifact